# ==========================================
# CONFIGURACIÓN DE CONEXIÓN (VARIABLES DE ENTORNO)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
# 'none' evita que Spring Boot modifique tus tablas manualmente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Permite que la aplicación arranque aunque la DB esté vacía al inicio
spring.jpa.defer-datasource-initialization=true